"""
Bybit P2P (OTC) client.

Same caveat as Binance: undocumented public endpoint, not the official
Bybit API. If fetch_ads logs "returned no usable data" with the raw
response attached, paste that back and the field mapping gets fixed in
one pass.

Bybit has no public, durable per-ad or per-merchant link (their only
"share this ad" mechanism must be generated by the merchant from their
own account and expires after 30 minutes) — so the link here stays a
generic link to the OTC trade page.
"""
import logging

import settings
from http_utils import post_with_retry

log = logging.getLogger(__name__)

URL = "https://api2.bybit.com/fiat/otc/item/online"

HEADERS = {
    "Content-Type": "application/json",
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    ),
}


def fetch_ads(trade_type: str, amount: float | None = None, fiat: str | None = None, rows: int = 10) -> list[dict]:
    """
    trade_type: "BUY" or "SELL" (same convention as binance_client).
    amount: trade size in the target fiat — see binance_client for why this exists.
    fiat: which currency to search against. Defaults to settings.FIAT.
    """
    amount = settings.MIN_TRADE_AMOUNT if amount is None else amount
    fiat = settings.FIAT if fiat is None else fiat
    side = "1" if trade_type == "BUY" else "0"

    body = {
        "userId": "",
        "tokenId": settings.ASSET,
        "currencyId": fiat,
        "payment": [],
        "side": side,
        "size": str(rows),
        "page": "1",
        "amount": str(int(amount)),
        "authMaker": False,
        "canTrade": False,
    }

    try:
        resp = post_with_retry(URL, json=body, headers=HEADERS, timeout=15)
        data = resp.json()
    except Exception as e:
        log.error("Bybit P2P request failed after retry (fiat=%s): %s", fiat, e)
        return []

    items = (data.get("result") or {}).get("items")
    if not items:
        log.warning("Bybit P2P returned no usable data for fiat=%s. Raw response: %s", fiat, data)
        return []

    offers = []
    for item in items:
        try:
            raw_methods = item.get("tradeMethods") or item.get("payments") or []
            methods = []
            if isinstance(raw_methods, list):
                for m in raw_methods:
                    if isinstance(m, dict):
                        name = m.get("payMethodName") or m.get("identifier")
                        if name:
                            methods.append(name)

            offers.append({
                "platform": "Bybit",
                "trade_type": trade_type,
                "fiat": fiat,
                "price": float(item["price"]),
                "merchant_name": item.get("nickName", "Unknown"),
                "completion_rate": float(item.get("recentExecuteRate") or 0) / 100,
                "order_count": int(item.get("recentOrderNum") or 0),
                "min_limit": float(item.get("minAmount") or 0),
                "max_limit": float(item.get("maxAmount") or 0),
                "available": float(item.get("lastQuantity") or 0),
                "payment_methods": methods,
                "adv_no": item.get("id", ""),
                "link": "https://www.bybit.com/fiat/trade/otc",
            })
        except (KeyError, TypeError, ValueError) as e:
            log.warning("Skipping malformed Bybit offer: %s", e)
            continue

    return offers
